
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dennis
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrame_Conexion = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_Material_coneccion = new javax.swing.JComboBox<String>();
        tf_Ancho_de_banda = new javax.swing.JTextField();
        tf_Longitud_Cable = new javax.swing.JTextField();
        bt_crearInstalacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_listaNodos = new javax.swing.JComboBox();
        bt_seleccionarNodo = new javax.swing.JButton();
        Jframe_crearPunto = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_NombrePunto = new javax.swing.JTextField();
        cb_tipoPunto = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        JFrame_Analisis = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jFrame_caminoCorto = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        bt_ev_caminoCorto = new javax.swing.JButton();
        bt_seleccionarVertices = new javax.swing.JButton();
        cb_paths = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_shortestPath = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jd_maxAncho = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        cb_nodosMax = new javax.swing.JComboBox();
        bt_evaluar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_maxAncho = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jd_costos = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_costos = new javax.swing.JTextArea();
        bt_costos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt_crearPunto = new javax.swing.JButton();
        bt_CrearRedes = new javax.swing.JButton();
        bt_Analisis = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        JFrame_Conexion.setName("Propiedades"); // NOI18N
        JFrame_Conexion.setResizable(false);

        jLabel3.setText("Material del Cable");

        jLabel4.setText("Longitud del Cable");

        jLabel5.setText("Ancho de Banda Soportado");

        jLabel6.setText("Nodo a conectar");

        cb_Material_coneccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cobre", "Fibra Optica" }));

        bt_crearInstalacion.setText("Crear");
        bt_crearInstalacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearInstalacionMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Creacion de Conexiones");

        jLabel8.setText("Metros");

        jLabel9.setText("Mb/s");

        bt_seleccionarNodo.setText("Seleccionar");
        bt_seleccionarNodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_seleccionarNodoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JFrame_ConexionLayout = new javax.swing.GroupLayout(JFrame_Conexion.getContentPane());
        JFrame_Conexion.getContentPane().setLayout(JFrame_ConexionLayout);
        JFrame_ConexionLayout.setHorizontalGroup(
            JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                .addGroup(JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                        .addGroup(JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                                        .addGap(263, 263, 263)
                                        .addGroup(JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tf_Longitud_Cable, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_Ancho_de_banda, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(39, 39, 39)
                                        .addGroup(JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)))
                                    .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                                        .addGroup(JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                                                .addGap(254, 254, 254)
                                                .addComponent(bt_seleccionarNodo))
                                            .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(cb_listaNodos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_Material_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(bt_crearInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JFrame_ConexionLayout.setVerticalGroup(
            JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFrame_ConexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addGroup(JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_listaNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_seleccionarNodo)
                    .addComponent(jLabel3)
                    .addComponent(cb_Material_coneccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_Ancho_de_banda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(JFrame_ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Longitud_Cable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(59, 59, 59)
                .addComponent(bt_crearInstalacion)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        Jframe_crearPunto.setResizable(false);

        jButton1.setText("Crear Punto");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel12.setText("Nombre ");

        jLabel13.setText("Tipo de Punto");

        tf_NombrePunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_NombrePuntoMouseClicked(evt);
            }
        });

        cb_tipoPunto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red Domestica", "Red Empresarial", "Antena Celular", "Conexion Dedicada" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Punto de Conexion");

        javax.swing.GroupLayout Jframe_crearPuntoLayout = new javax.swing.GroupLayout(Jframe_crearPunto.getContentPane());
        Jframe_crearPunto.getContentPane().setLayout(Jframe_crearPuntoLayout);
        Jframe_crearPuntoLayout.setHorizontalGroup(
            Jframe_crearPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Jframe_crearPuntoLayout.createSequentialGroup()
                .addGroup(Jframe_crearPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jframe_crearPuntoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(Jframe_crearPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Jframe_crearPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_tipoPunto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_NombrePunto)))
                    .addGroup(Jframe_crearPuntoLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        Jframe_crearPuntoLayout.setVerticalGroup(
            Jframe_crearPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jframe_crearPuntoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(Jframe_crearPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_NombrePunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jframe_crearPuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cb_tipoPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel2.setText("Analisis");

        jButton2.setText("Camino mas corto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Mayor ancho de banda");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Menores Costos");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JFrame_AnalisisLayout = new javax.swing.GroupLayout(JFrame_Analisis.getContentPane());
        JFrame_Analisis.getContentPane().setLayout(JFrame_AnalisisLayout);
        JFrame_AnalisisLayout.setHorizontalGroup(
            JFrame_AnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFrame_AnalisisLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(JFrame_AnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFrame_AnalisisLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFrame_AnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        JFrame_AnalisisLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3, jButton4});

        JFrame_AnalisisLayout.setVerticalGroup(
            JFrame_AnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFrame_AnalisisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        JFrame_AnalisisLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3, jButton4});

        jLabel11.setText("Camino mas corto");

        bt_ev_caminoCorto.setText("Evaluar");
        bt_ev_caminoCorto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ev_caminoCortoMouseClicked(evt);
            }
        });

        bt_seleccionarVertices.setText("Seleccionar");
        bt_seleccionarVertices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_seleccionarVerticesMouseClicked(evt);
            }
        });

        ta_shortestPath.setColumns(20);
        ta_shortestPath.setRows(5);
        jScrollPane1.setViewportView(ta_shortestPath);

        jButton5.setText("Limpiar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jFrame_caminoCortoLayout = new javax.swing.GroupLayout(jFrame_caminoCorto.getContentPane());
        jFrame_caminoCorto.getContentPane().setLayout(jFrame_caminoCortoLayout);
        jFrame_caminoCortoLayout.setHorizontalGroup(
            jFrame_caminoCortoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_caminoCortoLayout.createSequentialGroup()
                .addGroup(jFrame_caminoCortoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_caminoCortoLayout.createSequentialGroup()
                        .addGroup(jFrame_caminoCortoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame_caminoCortoLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel11))
                            .addGroup(jFrame_caminoCortoLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(cb_paths, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(bt_seleccionarVertices)
                                .addGap(44, 44, 44)
                                .addComponent(bt_ev_caminoCorto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jFrame_caminoCortoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jFrame_caminoCortoLayout.setVerticalGroup(
            jFrame_caminoCortoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_caminoCortoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame_caminoCortoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame_caminoCortoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jFrame_caminoCortoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_caminoCortoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_paths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_seleccionarVertices)
                            .addComponent(bt_ev_caminoCorto))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );

        jLabel15.setText("Maximo Ancho de Banda");

        bt_evaluar2.setText("Evaluar");
        bt_evaluar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_evaluar2MouseClicked(evt);
            }
        });

        ta_maxAncho.setColumns(20);
        ta_maxAncho.setRows(5);
        jScrollPane2.setViewportView(ta_maxAncho);

        jLabel16.setText("Nodos");

        jButton6.setText("Seleccionar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_maxAnchoLayout = new javax.swing.GroupLayout(jd_maxAncho.getContentPane());
        jd_maxAncho.getContentPane().setLayout(jd_maxAnchoLayout);
        jd_maxAnchoLayout.setHorizontalGroup(
            jd_maxAnchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                .addGroup(jd_maxAnchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                        .addGroup(jd_maxAnchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                                .addGroup(jd_maxAnchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel16))
                                    .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(bt_evaluar2)))
                                .addGap(106, 106, 106))
                            .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cb_nodosMax, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_maxAnchoLayout.setVerticalGroup(
            jd_maxAnchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(36, 36, 36)
                .addGroup(jd_maxAnchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jd_maxAnchoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_maxAnchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_nodosMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(bt_evaluar2)
                        .addGap(72, 72, 72))))
        );

        jLabel17.setText("Minimos Costos");

        ta_costos.setColumns(20);
        ta_costos.setRows(5);
        jScrollPane3.setViewportView(ta_costos);

        bt_costos.setText("Mostrar Menores Costos");
        bt_costos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_costosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_costosLayout = new javax.swing.GroupLayout(jd_costos.getContentPane());
        jd_costos.getContentPane().setLayout(jd_costosLayout);
        jd_costosLayout.setHorizontalGroup(
            jd_costosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_costosLayout.createSequentialGroup()
                .addGroup(jd_costosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_costosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jd_costosLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jd_costosLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(bt_costos)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jd_costosLayout.setVerticalGroup(
            jd_costosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_costosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_costos)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setName("Menu Principal"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOGO");

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        bt_crearPunto.setText("Crear Punto");
        bt_crearPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearPuntoMouseClicked(evt);
            }
        });

        bt_CrearRedes.setText("Crear Redes");
        bt_CrearRedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CrearRedesMouseClicked(evt);
            }
        });

        bt_Analisis.setText("Analisis");
        bt_Analisis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AnalisisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Analisis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_CrearRedes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(bt_crearPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_crearPunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_CrearRedes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_Analisis)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Menu Principal ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crearInstalacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearInstalacionMouseClicked
        boolean create = true;

        if (verticesTemporales.getSize() == 2 && verticesTemporales.get(0) != verticesTemporales.get(1)) {
            int tipoMaterial = this.cb_Material_coneccion.getSelectedIndex() + 1;
            int longitudCable = Integer.parseInt(this.tf_Longitud_Cable.getText());
            int anchoBanda = Integer.parseInt(this.tf_Ancho_de_banda.getText());

            if (tipoMaterial == 1 && anchoBanda > 100) {
                create = false;
                JOptionPane.showMessageDialog(this, "El Cobre no soporta ese ancho de banda", "ERROR", JOptionPane.WARNING_MESSAGE);
            } else if (tipoMaterial == 2 && anchoBanda > 10240) {
                create = false;
                JOptionPane.showMessageDialog(this, "La fibra no soporta ese ancho de banda", "ERROR", JOptionPane.WARNING_MESSAGE);
            }

            if (create) {
                if (principal.isAdyacente((Vertice) verticesTemporales.get(0), (Vertice) verticesTemporales.get(1)) == false) {
                    Arista conexion = new Arista((Vertice) verticesTemporales.get(0), (Vertice) verticesTemporales.get(1));
                    Arista conexion2 = new Arista((Vertice) verticesTemporales.get(1), (Vertice) verticesTemporales.get(0));
                    conexion.setMaterialConexion(tipoMaterial);
                    conexion.setAnchoBanda(anchoBanda);
                    conexion.setLongitudCable(longitudCable);
                    conexion2.setMaterialConexion(tipoMaterial);
                    conexion2.setAnchoBanda(anchoBanda);
                    conexion2.setLongitudCable(longitudCable);
                    principal.addEdge((Vertice) verticesTemporales.get(0), conexion);
                    principal.addEdge((Vertice) verticesTemporales.get(1), conexion2);
                    JOptionPane.showMessageDialog(null, "Conexion creada exitosamente");
                    this.limpiarPropiedadesdeConeccion();
                    contadorVertices = 0;
                    verticesTemporales = new Lista();
                    this.JFrame_Conexion.setVisible(false);
                    this.pack();
                    this.setLocationRelativeTo(this);
                    this.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Estos dos nodos ya poseen una conexion", "ERROR", JOptionPane.WARNING_MESSAGE);
                    this.limpiarPropiedadesdeConeccion();
                    contadorVertices = 0;
                    verticesTemporales = new Lista();
                    this.JFrame_Conexion.setVisible(false);
                    this.pack();
                    this.setLocationRelativeTo(this);
                    this.setVisible(true);
                }
            } else {
                this.limpiarPropiedadesdeConeccion();
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se cuentan con los nodos necesarios", "ERROR", JOptionPane.WARNING_MESSAGE);
            this.limpiarPropiedadesdeConeccion();
            contadorVertices = 0;
            verticesTemporales = new Lista();
            this.JFrame_Conexion.setVisible(false);
            this.pack();
            this.setLocationRelativeTo(this);
            this.setVisible(true);
        }
    }//GEN-LAST:event_bt_crearInstalacionMouseClicked

    private void bt_crearPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearPuntoMouseClicked
        this.mostrarventanapunto();
        this.limpiarPropiedadesdePunto();
    }//GEN-LAST:event_bt_crearPuntoMouseClicked

    private void bt_CrearRedesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CrearRedesMouseClicked
        this.listInComboBox(this.principal.getTodosVertices(), cb_listaNodos);
        this.setVisible(false);
        this.mostarventanaconexion();
    }//GEN-LAST:event_bt_CrearRedesMouseClicked

    private void bt_AnalisisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AnalisisMouseClicked
        this.listInComboBox(principal.getTodosVertices(), this.cb_paths);
        this.JFrame_Analisis.pack();
        this.JFrame_Analisis.setLocationRelativeTo(this);
        this.JFrame_Analisis.setVisible(true);

    }//GEN-LAST:event_bt_AnalisisMouseClicked

    private void tf_NombrePuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_NombrePuntoMouseClicked

    }//GEN-LAST:event_tf_NombrePuntoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre = this.tf_NombrePunto.getText();
        int typePunto = this.cb_tipoPunto.getSelectedIndex() + 1;
        Instalacion nuevopunto = new Instalacion(nombre, typePunto);
        this.principal.addVertice(nuevopunto);
        JOptionPane.showMessageDialog(null, "Punto creado exitosamente");
        this.Jframe_crearPunto.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_seleccionarNodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_seleccionarNodoMouseClicked
        if (contadorVertices < 2) {
            this.verticesTemporales.push(this.cb_listaNodos.getSelectedItem());
            contadorVertices++;
            JOptionPane.showMessageDialog(this, "Nodo seleccionado correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Ya eligio los nodos necesarios", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_seleccionarNodoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.jFrame_caminoCorto.pack();
        this.jFrame_caminoCorto.setLocationRelativeTo(this);
        this.jFrame_caminoCorto.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void bt_seleccionarVerticesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_seleccionarVerticesMouseClicked
        if (contadorVertices < 2) {
            this.verticesTemporales.push((this.cb_paths.getSelectedItem()));
            this.contadorVertices++;
            JOptionPane.showMessageDialog(this, "Nodo seleccionado correctamente", "", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Ya eligio los nodos necesarios", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_seleccionarVerticesMouseClicked

    private void bt_ev_caminoCortoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ev_caminoCortoMouseClicked
        if (contadorVertices == 2) {
            Lista caminoCorto = new Lista();
            caminoCorto = principal.caminoMasCorto((Vertice)verticesTemporales.get(0), (Vertice)verticesTemporales.get(1));
            this.ta_shortestPath.setText("");
            for (int i = 0; i < caminoCorto.getSize(); i++) {
                this.ta_shortestPath.append(i+1 + " " + caminoCorto.get(i)+"\n");
            }
            contadorVertices = 0;
            this.verticesTemporales = new Lista();
            
        } else {
            JOptionPane.showMessageDialog(this, "NO hay los nodos necesarios para la operacion", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_ev_caminoCortoMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
            contadorVertices = 0;
            this.verticesTemporales = new Lista();
            this.ta_shortestPath.setText("");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       this.JFrame_Analisis.setVisible(false);
       listInComboBox(principal.getTodosVertices(), this.cb_nodosMax);
       this.jd_maxAncho.pack();
       this.jd_maxAncho.setLocationRelativeTo(this);
       this.jd_maxAncho.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void bt_evaluar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_evaluar2MouseClicked
        this.ta_maxAncho.setText("");
        if(contadorVertices == 2){
            Lista lista = new Lista();
            lista = principal.mayorAnchoBanda((Vertice)verticesTemporales.get(0), (Vertice)verticesTemporales.get(1));
            
            for (int i = 0; i < lista.getSize(); i++) {
                this.ta_maxAncho.append( (i+1) + " "  + lista.get(i) + "\n");
            }
            
            contadorVertices = 0;
            verticesTemporales = new Lista();
        }else{
            JOptionPane.showMessageDialog(this, "No hay un numero correcto de nodos");
        }
    }//GEN-LAST:event_bt_evaluar2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if(contadorVertices < 2){
            verticesTemporales.push(this.cb_nodosMax.getSelectedItem());
            contadorVertices++;
            JOptionPane.showMessageDialog(this, "Nodo agregado exitosamente");
        }else{
            JOptionPane.showMessageDialog(this, "Numero de nodos excedidos");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        this.JFrame_Analisis.setVisible(false);
        this.ta_costos.setText("");
        this.jd_costos.pack();
        this.jd_costos.setLocationRelativeTo(this);
        this.jd_costos.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void bt_costosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_costosMouseClicked
        this.ta_costos.setText("");
        Lista mostrar = new Lista();
        mostrar = principal.menoresCostos();
        
        for (int i = 0; i < mostrar.getSize(); i++) {
            ta_costos.append(i+1 + " ");
            ta_costos.append("Para llegar a: " + ((Lista)mostrar.get(i)).get(((Lista)mostrar.get(i)).getSize()-1) + "\n");
            for (int k = 0; k < ((Lista)mostrar.get(i)).getSize(); k++) {
                ta_costos.append(((Lista)mostrar.get(i)).get(k) + "||");
            }
            ta_costos.append("\n");
        }
    }//GEN-LAST:event_bt_costosMouseClicked

    public void listInComboBox(Lista list, JComboBox cb) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < list.getSize(); i++) {
            modelo.addElement(((Vertice) list.get(i)));
        }
        cb.setModel(modelo);
    }

    private void limpiarPropiedadesdePunto() {
        this.tf_NombrePunto.setText("");
    }

    private void mostrarventanapunto() {
        this.Jframe_crearPunto.pack();
        this.Jframe_crearPunto.setLocationRelativeTo(this);
        this.Jframe_crearPunto.setVisible(true);
    }

    private void mostarventanaconexion() {
        this.JFrame_Conexion.pack();
        this.JFrame_Conexion.setLocationRelativeTo(this);
        this.JFrame_Conexion.setVisible(true);
    }

    private void limpiarPropiedadesdeConeccion() {
        this.cb_Material_coneccion.setSelectedIndex(0);
        this.tf_Ancho_de_banda.setText("");
        this.tf_Longitud_Cable.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame JFrame_Analisis;
    private javax.swing.JFrame JFrame_Conexion;
    private javax.swing.JFrame Jframe_crearPunto;
    private javax.swing.JButton bt_Analisis;
    private javax.swing.JButton bt_CrearRedes;
    private javax.swing.JButton bt_costos;
    private javax.swing.JButton bt_crearInstalacion;
    private javax.swing.JButton bt_crearPunto;
    private javax.swing.JButton bt_ev_caminoCorto;
    private javax.swing.JButton bt_evaluar2;
    private javax.swing.JButton bt_seleccionarNodo;
    private javax.swing.JButton bt_seleccionarVertices;
    private javax.swing.JComboBox<String> cb_Material_coneccion;
    private javax.swing.JComboBox cb_listaNodos;
    private javax.swing.JComboBox cb_nodosMax;
    private javax.swing.JComboBox<String> cb_paths;
    private javax.swing.JComboBox<String> cb_tipoPunto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame_caminoCorto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_costos;
    private javax.swing.JDialog jd_maxAncho;
    private javax.swing.JTextArea ta_costos;
    private javax.swing.JTextArea ta_maxAncho;
    private javax.swing.JTextArea ta_shortestPath;
    private javax.swing.JTextField tf_Ancho_de_banda;
    private javax.swing.JTextField tf_Longitud_Cable;
    private javax.swing.JTextField tf_NombrePunto;
    // End of variables declaration//GEN-END:variables
    Grafo principal = new Grafo(new Vertice(new Instalacion("Principal", 2)));
    int tipoPunto;
    Vertice main = new Vertice();
    Lista verticesTemporales = new Lista();
    int contadorVertices = 0;
}
